# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nokeya/wav2mp3Converter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nokeya/wav2mp3Converter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nokeya/wav2mp3Converter/CMakeFiles /home/nokeya/wav2mp3Converter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nokeya/wav2mp3Converter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wav2mp3Converter

# Build rule for target.
wav2mp3Converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wav2mp3Converter
.PHONY : wav2mp3Converter

# fast build rule for target.
wav2mp3Converter/fast:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/build
.PHONY : wav2mp3Converter/fast

fileUtils.o: fileUtils.cpp.o

.PHONY : fileUtils.o

# target to build an object file
fileUtils.cpp.o:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/fileUtils.cpp.o
.PHONY : fileUtils.cpp.o

fileUtils.i: fileUtils.cpp.i

.PHONY : fileUtils.i

# target to preprocess a source file
fileUtils.cpp.i:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/fileUtils.cpp.i
.PHONY : fileUtils.cpp.i

fileUtils.s: fileUtils.cpp.s

.PHONY : fileUtils.s

# target to generate assembly for a file
fileUtils.cpp.s:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/fileUtils.cpp.s
.PHONY : fileUtils.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/main.cpp.s
.PHONY : main.cpp.s

platform.o: platform.cpp.o

.PHONY : platform.o

# target to build an object file
platform.cpp.o:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/platform.cpp.o
.PHONY : platform.cpp.o

platform.i: platform.cpp.i

.PHONY : platform.i

# target to preprocess a source file
platform.cpp.i:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/platform.cpp.i
.PHONY : platform.cpp.i

platform.s: platform.cpp.s

.PHONY : platform.s

# target to generate assembly for a file
platform.cpp.s:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/platform.cpp.s
.PHONY : platform.cpp.s

posix_thread.o: posix_thread.cpp.o

.PHONY : posix_thread.o

# target to build an object file
posix_thread.cpp.o:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/posix_thread.cpp.o
.PHONY : posix_thread.cpp.o

posix_thread.i: posix_thread.cpp.i

.PHONY : posix_thread.i

# target to preprocess a source file
posix_thread.cpp.i:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/posix_thread.cpp.i
.PHONY : posix_thread.cpp.i

posix_thread.s: posix_thread.cpp.s

.PHONY : posix_thread.s

# target to generate assembly for a file
posix_thread.cpp.s:
	$(MAKE) -f CMakeFiles/wav2mp3Converter.dir/build.make CMakeFiles/wav2mp3Converter.dir/posix_thread.cpp.s
.PHONY : posix_thread.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... wav2mp3Converter"
	@echo "... fileUtils.o"
	@echo "... fileUtils.i"
	@echo "... fileUtils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... platform.o"
	@echo "... platform.i"
	@echo "... platform.s"
	@echo "... posix_thread.o"
	@echo "... posix_thread.i"
	@echo "... posix_thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

